config/routes.rb
Rails.application.routes.draw do
  get 'attendances/index'
	root to: 'events#index'
  devise_for :users
  get 'events/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :users, only: [:show, :edit, :update]
  resources :attendances, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :participant, class_name: "User"
	belongs_to :event

	after_create :new_participant_send

	def new_participant_send
    	UserMailer.new_participant_email(self).deliver_now
 	end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :admin, class_name: "User"
	has_many :attendances
	has_many :participants, through: :attendances

	validates :start_date,
	presence: true

	validates :duration,
	presence: true,
	numericality: { :greater_than => 0, only_integer: true}

	validates :title,
	presence: true,
	length: {in: 5..140}

	validates :description,
	presence: true,
	length: {in: 20..1000}

	validates :price,
	presence: true,
	numericality: { greater_than: 0, less_than: 1000, only_integer: true}

	validates :location,
	presence: true

	validate :start_must_be_in_future
	validate :duration_must_be_multiple_of_five

	def end_date
    	self.start_date + self.duration.minutes
  	end
	private
  # VALIDATION METHODS
  def start_must_be_in_future
    errors.add(:start_date, "Start date must be in the future") unless start_date.present? && start_date > Date.today
  end
  def duration_must_be_multiple_of_five
    errors.add(:duration, "Must be a multiple of 5") unless self.duration.to_i % 5 == 0
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances, foreign_key: 'participant_id'
	has_many :events, through: :attendances
	
	after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit]
  def index
  	@events = Event.all
  end
  def show
  	@event = Event.find(params[:id])
  end
  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.create!(title: params[:title],description: params[:description], start_date: params[:start_date], duration: params[:duration], price: params[:price], location: params[:location], admin_id: current_user.id)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end
  def update
    @event = Event.find(params[:id])
    if @event.update(title: params[:title],description: params[:description], start_date: params[:start_date], duration: params[:duration], price: params[:price], location: params[:location])
      flash[:success] = "Event Update!"
      redirect_to event_path(@event.id)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
  	before_action :own_profile, only: [:show]
  
  def show
  end

  def update
    @user = User.find(params[:id])
    if @user.update(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], description: params[:description])
      flash[:success] = "Profile Update!"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def own_profile
    if params[:id].to_i == current_user.id
    else
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def  new_event
    Event.new
  end

  def current_event
    Event.find(@event.id)
  end

  def event_end_date
   	event_end_at = @event.start_date + @event.duration.minutes
  end

  def admin_event_email
    User.find(current_event.admin_id).email
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/events/edit.html.erb
<div class="container" >
  	<div class="row">
  		<div class="col-md-8 mx-auto mt-5">

      	<%= form_tag url_for(action: "update"), method: "put" do |f| %>
        <%= label_tag 'Start_Date' %>
        <%= text_field_tag 'start_date', @event.start_date, class: 'form-control'%>
        <%= label_tag 'Duration' %>
        <%= text_field_tag 'duration', @event.duration, class: 'form-control'%>
        <%= label_tag 'Location' %>
        <%= text_field_tag 'location', @event.location, class: 'form-control'%>
        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', @event.title, class: 'form-control'%>
        <%= label_tag 'Description' %>
        <%= text_field_tag 'description', @event.description, class: 'form-control'%>
        <%= label_tag 'Price' %>
        <%= text_field_tag 'price', @event.price, class: 'form-control'%>
        <br/>
        <%= submit_tag "Modify event", class: 'btn btn-lg btn-primary btn-block' %>

      <% end %>

  		</div>
  	</div>
  </div>  

app/views/events/index.html.erb
<div class="container">
  <div class="row flex-row">
    <div class="col d-flex justify-content-center mt-3">
      <h2>Tous les évènements :</h2>
    </div>
  </div>
  
  <div class="row">
    <%@events.all.each do |event|%>
      <div class="text-center col-md-4 mb-5 my-5">
        <h3><%= event.title.capitalize!%></h3>
        <h4 class="text-center card-subtitle mb-2 text-muted">by <%= User.find(event.admin_id).first_name%> </h4>
        <p class="text-center card-text"><%= event.description%></p> 
        <p><a href="<%= event_path(event.id)%>" class="btn btn-info">Voir l'event</a></p>
      </div>
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
<div class="container" >
    <div class="row">
      <div class="col-md-8 mx-auto mt-5">

        <%= form_tag url_for(action: "create"), method: "post" do %>
        <%= label_tag 'Start_Date' %>
        <%= text_field_tag 'start_date', new_event.start_date, class: 'form-control'%>
        <%= label_tag 'Duration' %>
        <%= text_field_tag 'duration', new_event.duration, class: 'form-control'%>
        <%= label_tag 'Location' %>
        <%= text_field_tag 'location', new_event.location, class: 'form-control'%>
        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', new_event.title, class: 'form-control'%>
        <%= label_tag 'Description' %>
        <%= text_field_tag 'description', new_event.description, class: 'form-control'%>
        <%= label_tag 'Price' %>
        <%= text_field_tag 'price', new_event.price, class: 'form-control'%>
        <br/>
        <%= submit_tag "Create event", class: 'btn btn-lg btn-primary btn-block' %>

      <% end %>

      </div>
    </div>
  </div>  

app/views/events/show.html.erb
<div class="container show_event">
  <div class="col text-center">
    <h2>Event n°<%=@event.id%></h2><br>
  </div>

  <div class="card mx-3">
    <div class="card-header">
      <strong><%= @event.title%></strong>
    </div>

    <div class="card-body px-4">

      <br/>   
      <p><strong>Price :</strong> <%= @event.price%></p>
      <p><strong>Duration:</strong><%= @event.duration%> min</p>
      <p><strong>Participation :</strong> <%= Attendance.where(event_id: @event.id).count  %></p>
      <p><strong>Administrator mail :</strong> <%= admin_event_email%></p>
      <p><strong>Start at :</strong> <%= @event.start_date%></p>
      <p><strong>End at :</strong> <%=event_end_date%></p>
      <p><strong>Location :</strong> <%= @event.location%></p>
      <blockquote class="blockquote mb-0">
        <em>"<%= @event.description %>"</em><p></p>
        <footer class="blockquote-footer">
          <p>By : <a href="<%= user_path(current_user) %>" class="card-link"><%= @event.admin.first_name%> <%= @event.admin.last_name %></a></p>
          <p>Create: <%= @event.created_at %></p>

          <div class="row flex-row">
            <%if current_user%>
              <%if current_user.id == @event.admin_id%>
                <a href="<%=edit_event_path(@event.id)%>" class="btn btn-info ml-4">Edit event</a>
                <%= form_tag url_for(action: 'destroy'), method: "delete" do%>
                  <%= submit_tag "Delete event", class: 'btn btn-danger ml-3'%>
                <%end%>
              <%end%>
              <%else%>
                <span class="d-flex align-items-center">Login to edit your event</span>
           <%end%>
          </div>

        </footer>
      </blockquote>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheEventProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    


  </head>

  <body>
  
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%=root_path%>">Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Créer Evènement", new_event_path, :method => 'get', class: "nav-link"%>
          </li>     
          
          <%if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Mon Profil
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Mon profile", user_path(current_user), :method => 'get', class: "dropdown-item"%>
                <%= link_to "Déconnexion", destroy_user_session_path, :method => 'delete', class: "dropdown-item"%>
              </div>
            </li>
          <%else%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                S'inscrire / Se connecter
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "S'inscrire", new_user_registration_path, :method => 'get', class: "dropdown-item"%>
              <%= link_to "Se connecter", new_user_session_path, :method => 'get', class: "dropdown-item"%>
              </div>
            </li>
          <%end%>
        </ul>
      </div>
    </nav>
  
    <%= yield %>

    <footer class="footer bg-dark">
      <div class="container text-center py-2">
        <p class="text-muted small"> ☀ Créée par Rianah Ounie ☀<a href="https://github.com/Rianasoa"> 🧙‍♂️ Rianasoa</a></p>        
      </div> 
    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    

  </body>
</html>

app/views/users/edit.html.erb
<div class="container" >
  	<div class="row">
  		<div class="col-md-8 mx-auto mt-5">

      	<%= form_tag url_for(action: "update"), method: "put" do |f| %>
        <%= label_tag 'First name' %>
        <%= text_field_tag 'first_name', current_user.first_name, class: 'form-control'%>
        <%= label_tag 'Last name' %>
        <%= text_field_tag 'last_name', current_user.last_name, class: 'form-control'%>
        <%= label_tag 'Description' %>
        <%= text_field_tag 'description', current_user.last_name, class: 'form-control'%>
        <%= label_tag 'email' %>
        <%= text_field_tag 'email', current_user.email, class: 'form-control'%>
        <br/>
        <%= submit_tag "Modify profil", class: 'btn btn-lg btn-primary btn-block' %>

      <% end %>

  		</div>
  	</div>
  </div>  

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1 class="my-3"><%=current_user.first_name%>'s profile page</h1>
    </div>
  </div>

  <div class="row flex-row">
    <div class="col">
      <h2>My informations</h2>
      <ul>
        <li><%=current_user.first_name%> <%=current_user.last_name%></li><br>
        <li><%=current_user.description%></li><br>
        <li><%=current_user.email%></li>
      </ul>
      <br><br>
      <h2>My events</h2>
        <div class="row">
        <% Event.all.each do |event|%>
          <%if event.admin_id == current_user.id%>
          <div class="text-center col-md-4 mb-5 my-5">
            <h2><%= event.title.capitalize!%></h2>
            <h3 class="text-center card-subtitle mb-2 text-muted">by<%= event.admin.first_name%> </h3>
            <p class="text-center card-text"><%= event.description%></p> 
            <p><%= link_to "See the event", event_path(event.id), :method => 'get', class: "btn btn-info"%></p>
          </div>
          <%end%>
        <%end%>
      </div>
      <br><%= link_to "Edit my informations", edit_user_path(current_user), :method => 'get', class: "btn btn-info d-flex justify-content-end"%><br><br>
    </div>
  </div>